/******************************************************************/
/* Author	: Mahmoud Rajab										  */
/* Date		: 9 Sep 2021										  */
/* Version	: V01												  */
/******************************************************************/



#ifndef 7_SEGMENT_PRIVATE_H
#define 7_SEGMENT_PRIVATE_H


/* Seven Segment Values */

static volatile const u8 G_SevenSegment[10][7] =
				 	 {	{GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW },
						{GPIO_PIN_LOW , GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_LOW , GPIO_PIN_LOW , GPIO_PIN_LOW },
						{GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_HIGH},
						{GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_LOW , GPIO_PIN_HIGH},
						{GPIO_PIN_LOW , GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_LOW , GPIO_PIN_HIGH, GPIO_PIN_HIGH},
						{GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_HIGH, GPIO_PIN_HIGH},
						{GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH},
						{GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_LOW , GPIO_PIN_LOW , GPIO_PIN_LOW },
						{GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH},
						{GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_HIGH, GPIO_PIN_LOW , GPIO_PIN_HIGH, GPIO_PIN_HIGH}	};


#endif